spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=glailtonnascimento88@gmail.com
spring.mail.password=vwwemehabaksdkys
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.application.name=vitacontrol-demo
spring.datasource.url=jdbc:postgresql://dpg-d8blussua31s739balm0-a.frankfurt-postgres.render.com:5432/vitacontrol_demo
spring.datasource.username=vitacontrol_user
spring.datasource.password=c5kwN1GVZr1t91UmMatTpqO4LIhPo3B2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ajustes para estabilizar a conexão com o PostgreSQL
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000

